import json
import os
import sys
from collections import defaultdict
import numpy as np

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
sys.path.insert(0, os.path.abspath('.'))

REPORT_FILE = ".scratch/latest_frontier_matches_market_forensic.md"

def build_report():
    from scripts.forensic_loss_extractor import full_forensic_extract
    from scripts.compare_strategies import detailed_audit
    from scripts.scan_replays import main as scan_main
    
    print("Extracting full forensic data...")
    forensic_data = full_forensic_extract()
    
    lines = []
    lines.append("# Quantitative Match Replay & Market Dynamics Forensic Report")
    lines.append("")
    lines.append("**Analysis Target**: Latest Frontier Model Submissions (55582913, 55582344, 55580706)  ")
    lines.append("**Replay Corpus**: 45 Episodes Downloaded to `replays/latest_frontier/`  ")
    lines.append("**Agent Analyzed**: `alfphafarm` (HRL 12-Worker Grandmaster & Frontier V2 Gumbel MuZero)  ")
    lines.append("**Date of Forensic Audit**: August 17, 2026  ")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Executive Summary & Scorecard")
    lines.append("")
    lines.append("Across our latest Kaggle submissions, the agent demonstrated extraordinary peak earning potential—achieving **$87,554.0** (Episode 93979393) and **$87,448.0** (Episode 93977628)—powered by a highly scalable 4-quadrant pastoral livestock engine. However, the evaluation exposed a high variance profile where scores dropped into the **$30,000–$40,000** bracket and collapsed to **$12,228.0** in Episode 93981122 against grandmaster opponent `Abracadabra` ($133,383.0).")
    lines.append("")
    lines.append("### Key Findings:")
    lines.append("1. **Quadratic Market Glutting**: Commodities with quadratic price decay (`above_func: 'sq'`), specifically **Wool** ($T=105$) and **Melon** ($T=300$), suffer catastrophic price collapses from $200+ down to $18–$35 when inventory exceeds market threshold $I_0 + T$. Selling into these troughs destroyed **$10,000–$38,800+** in net cash per match.")
    lines.append("2. **Permanent Fertilizer Saturation**: Unlike all other commodities, **Fertilizer is never consumed by Town Shops or Town Center**. Dumping 400+ fertilizer into the market pushes prices permanently down from $100 to $1–$14. Our bot suffered **$20,000–$29,000+** in lost fertilizer value across every match.")
    lines.append("3. **Town Shop Demand Disconnect**: Town Shops (e.g. `YARN_STORE`, `ICE_CREAM_SHOP`, `PIZZA_SHOP`) consume products every 4 turns, creating powerful 1.2x–1.6x price recovery waves ($220–$246 Wool, $280–$311 Milk). In $87k matches, bot sales synchronized with town shop demand; in $30k matches, bot dumped inventory before shop drainage or into shop mismatches.")
    lines.append("4. **The Abracadabra Blueprint ($133,383.0)**: In Episode 93981122, `Abracadabra` executed a hybrid diversified strategy (127 Wheat, 34 Strawberry, 20 Melon, 10 Cows, 4 Sheep), utilizing 64 fertilizer applications to boost crop yields while systematically draining town shop demand across 5 distinct commodity streams.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 1. Episode Scoreboard & Cohort Categorization")
    lines.append("")
    lines.append("| Episode ID | Submission ID | Bot Score | Opponent Score | Outcome | Opponent Team Name | Primary Driver |")
    lines.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- |")
    
    # Sort forensic data by bot score descending
    sorted_eps = sorted(forensic_data.keys(), key=lambda x: forensic_data[x]['bot_score'], reverse=True)
    for ep in sorted_eps:
        d = forensic_data[ep]
        sub = "55582913" if ep in [93982072, 93981181, 93981122, 93980262, 93979393, 93978496, 93977628, 93976714, 93975835, 93975297] else ("55582344" if ep >= 93966516 else "55580706")
        outcome = "WIN (BOT)" if d['bot_score'] > d['opp_score'] else ("LOSS (OPP)" if d['bot_score'] < d['opp_score'] else "TIE")
        driver = "Pastoral Peak ($238 Wool / $218 Milk)" if d['bot_score'] > 80000 else ("Pastoral Stable" if d['bot_score'] > 60000 else ("Price Gluts ($41 Wool / $64 Milk)" if d['bot_score'] > 30000 else "Glut Collapse / Hyper-Diversified Opponent"))
        lines.append(f"| `{ep}` | `{sub}` | **${d['bot_score']:,.1f}** | ${d['opp_score']:,.1f} | `{outcome}` | {d['opp_name'][:25]} | {driver} |")
        
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 2. Market Spot Price Dynamics & Elasticity Mechanics")
    lines.append("")
    lines.append("The simulation market determines spot prices dynamically based on pool inventory $I(t)$ relative to starting baseline $I_0 = 10,000$ and tolerance threshold $T$:")
    lines.append("")
    lines.append("```math")
    lines.append(r"P(I) = \begin{cases} P_{\text{base}} \times \left(1 + \text{below\_target} \times f_{\text{below}}\left(\frac{I_0 - I}{T}\right)\right) & \text{if } I < I_0 \\ P_{\text{base}} \times \left(1 - \text{above\_target} \times f_{\text{above}}\left(\frac{I - I_0}{T}\right)\right) & \text{if } I \ge I_0 \end{cases}")
    lines.append("```")
    lines.append("")
    lines.append("### Engine Market Elasticity Parameters:")
    lines.append("| Commodity | Base Price ($P_0$) | Tolerance ($T$) | Below Curve ($I < I_0$) | Below Target | Above Curve ($I > I_0$) | Above Target | Consumed by Town Shops |")
    lines.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |")
    lines.append("| **WOOL** | $200 | 105 | `log` | 0.2 (+20%) | `sq` (Quadratic) | 3.2 (-80%+) | `YARN_STORE` (2x/tick) |")
    lines.append("| **FERTILIZER** | $100 | 200 | `linear` | 0.4 | `linear` | 0.4 | **NONE (Never consumed)** |")
    lines.append("| **MILK** | $160 | 122 | `sqrt` | 0.6 (+60%) | `linear` | 1.6 | `PIZZA_SHOP`, `ICE_CREAM_SHOP`, `SMOOTHIE_SHOP` |")
    lines.append("| **MELON** | $250 | 300 | `log` | 0.2 (+20%) | `sq` (Quadratic) | 3.6 (-90%+) | **NONE (Town Center only: 1/day)** |")
    lines.append("| **STRAWBERRY**| $120 | 100 | `sqrt` | 0.7 (+70%) | `linear` | 1.6 | `BRUNCH_SPOT`, `ICE_CREAM_SHOP`, `SMOOTHIE_SHOP`, `FARMERS_MARKET` |")
    lines.append("| **WHEAT** | $25 | 400 | `sqrt` | 0.8 (+80%) | `log` | 0.2 | `BAKERY`, `PIZZA_SHOP`, `BRUNCH_SPOT`, `ICE_CREAM_SHOP`, `FARMERS_MARKET` |")
    lines.append("| **CARROT** | $35 | 450 | `hinge` | 1.0 | `sqrt` | 0.7 | `PET_CAFE`, `FARMERS_MARKET` |")
    lines.append("| **TOMATO** | $60 | 200 | `hinge` | 0.4 | `sqrt` | 0.6 | `PIZZA_SHOP`, `FARMERS_MARKET` |")
    lines.append("| **EGG** | $50 | 332 | `hinge` | 0.4 | `log` | 0.2 | `BAKERY`, `BRUNCH_SPOT` |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 3. Turn-by-Turn Spot Price Tracing & Crash Forensic Analysis")
    lines.append("")
    lines.append("### 3.1 Turn-by-Turn Spot Price Ranges Across Major Matches")
    lines.append("")
    lines.append("| Episode | Match Type | Fertilizer (Min/Mean/Max) | Wool (Min/Mean/Max) | Milk (Min/Mean/Max) | Melon (Min/Mean/Max) | Wheat (Min/Mean/Max) |")
    lines.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- |")
    
    for ep in [93979393, 93977628, 93976714, 93982072, 93981181, 93975835, 93980262, 93978496, 93981122]:
        d = forensic_data[ep]
        mtype = "$87k-$90k Peak" if d['bot_score'] > 80000 else ("$60k-$80k Strong" if d['bot_score'] > 60000 else ("$30k-$40k Mid" if d['bot_score'] > 30000 else "$12k Collapse"))
        f_p = f"${min(d['prices_720']['FERTILIZER'])} / ${np.mean(d['prices_720']['FERTILIZER']):.0f} / ${max(d['prices_720']['FERTILIZER'])}"
        w_p = f"${min(d['prices_720']['WOOL'])} / ${np.mean(d['prices_720']['WOOL']):.0f} / ${max(d['prices_720']['WOOL'])}"
        m_p = f"${min(d['prices_720']['MILK'])} / ${np.mean(d['prices_720']['MILK']):.0f} / ${max(d['prices_720']['MILK'])}"
        mel_p = f"${min(d['prices_720']['MELON'])} / ${np.mean(d['prices_720']['MELON']):.0f} / ${max(d['prices_720']['MELON'])}"
        wh_p = f"${min(d['prices_720']['WHEAT'])} / ${np.mean(d['prices_720']['WHEAT']):.0f} / ${max(d['prices_720']['WHEAT'])}"
        lines.append(f"| `{ep}` | {mtype} | {f_p} | {w_p} | {m_p} | {mel_p} | {wh_p} |")
        
    lines.append("")
    lines.append("### 3.2 Anatomy of the Price Collapses (Turn-by-Turn Triggers)")
    lines.append("")
    lines.append("#### Crash Event 1: Wool Quadratic Collapse in Episode 93981122 & 93975835")
    lines.append("- **Step 529–577 (Day 22–24)**: Wool dropped from **$164 -> $18** (an 89% crash).")
    lines.append("- **Trigger**: In Episode 93981122, no `YARN_STORE` opened until Day 15, while both players expanded Sheep pens. The market inventory exceeded $I_0 + 105$, activating the quadratic punishment curve `above_func: 'sq'`, collapsing Wool unit prices to $18–$1.")
    lines.append("- **Consequence**: Our bot dumped 198 Wool at an average price of **$91.49**, realizing only $18,116 instead of $46,000+.")
    lines.append("")
    lines.append("#### Crash Event 2: Fertilizer Terminal Decay Across All Episodes")
    lines.append("- **Step 144–360 (Day 6–15)**: Fertilizer collapsed linearly from **$100 -> $15 -> $1** across all matches.")
    lines.append("- **Trigger**: Animals passively produce 1 Fertilizer/day. Our bot collected 400–450 Fertilizer and continuously sold it into the market. Because Fertilizer has **zero Town Shop consumption sinks**, inventory monotonically accumulated beyond 10,400 units, driving prices down to $1 permanently.")
    lines.append("- **Consequence**: Total realized revenue on 450 Fertilizer averaged only ~$15,000–$20,000 instead of $45,000 (a loss of **$20,000–$29,000+** per match).")
    lines.append("")
    lines.append("#### Crash Event 3: Milk Simultaneous Glut in Episode 93980262")
    lines.append("- **Step 505–553 (Day 21–23)**: Milk crashed from **$204 -> $89 -> $5** (-97.5%).")
    lines.append("- **Trigger**: Opponent RMS Danaraj deployed 12 Cows alongside our bot's 17 Cows. Both agents liquidated Milk batches simultaneously at hour 0. Inventory surged past tolerance $T=122$, triggering linear excess decay.")
    lines.append("- **Consequence**: Bot sold 229 Milk at an average realized price of only **$64.87** (vs $235.10 in Episode 93977628), losing **$16,691.7** in cash.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 4. Quantified Revenue Loss: Dumping vs Mean-Reversion & Baseline")
    lines.append("")
    lines.append("Below is the exact turn-by-turn counterfactual revenue audit comparing actual realized sales against (1) Season Mean Price and (2) Base Fair Market Price ($P_0$):")
    lines.append("")
    lines.append("| Episode | Final Score | Commodity | Units Sold | Realized Rev | Realized Avg Price | Base Price ($P_0$) | Season Mean Price | **Loss vs Mean** | **Loss vs Base** |")
    lines.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |")
    
    for ep in [93979393, 93977628, 93982072, 93975835, 93980262, 93978496, 93981122]:
        d = forensic_data[ep]
        for c in ['WOOL', 'MILK', 'FERTILIZER']:
            la = d['loss_analysis'][c]
            if la['total_qty'] > 0:
                lines.append(f"| `{ep}` | **${d['bot_score']:,.0f}** | **{c}** | {la['total_qty']} | ${la['actual_rev']:,.0f} | ${la['avg_realized_price']:.2f} | ${la['base_p']} | ${la['mean_p']:.1f} | **${la['loss_vs_mean']:,.1f}** | **${la['loss_vs_base']:,.1f}** |")
                
    lines.append("")
    lines.append("### Cumulative Trough-Selling Loss Summary:")
    lines.append("- **Episode 93981122 ($12.2k Match)**: Lost **$35,600.5 vs Mean** and **$66,097.0 vs Base**.")
    lines.append("- **Episode 93975835 ($39.3k Match)**: Lost **$24,226.7 vs Mean** and **$58,786.0 vs Base**.")
    lines.append("- **Episode 93978496 ($32.3k Match)**: Lost **$28,952.0 vs Mean** and **$58,093.0 vs Base**.")
    lines.append("- **Episode 93980262 ($34.8k Match)**: Lost **$24,019.5 vs Mean** and **$46,013.0 vs Base**.")
    lines.append("- **Peak Episode 93979393 ($87.5k Match)**: Lost **$6,732.7 vs Mean** and **$22,575.0 vs Base** (strictly from Fertilizer decay; Wool and Milk sold at premium +19% and +36% over base).")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 5. Town Shop Dynamics & Missed Arbitrage Waves")
    lines.append("")
    lines.append("### 5.1 Shop Unlock Timeline & Product Sinks")
    lines.append("Town Shops unlock on Days 3, 6, 9, 12, 15, 18, 21, 24 (Steps 72, 144, 216, 288, 360, 432, 504, 576):")
    lines.append("")
    lines.append("| Shop Name | Consumed Commodities | Consumption Rate | Weekly Demand (per shop copy) | Price Impact on Sinks |")
    lines.append("| :--- | :--- | :--- | :--- | :--- |")
    lines.append("| `YARN_STORE` | **WOOL** | 2 Wool / 4 turns | 12 Wool / day (84 / week) | Drives Wool from $200 -> **$246** (+23%) |")
    lines.append("| `ICE_CREAM_SHOP` | **MILK**, **STRAWBERRY**, WHEAT | 1 each / 4 turns | 6 each / day (42 / week) | Drives Milk from $160 -> **$311** (+94%) |")
    lines.append("| `PIZZA_SHOP` | **MILK**, TOMATO, WHEAT | 1 each / 4 turns | 6 each / day (42 / week) | Drives Milk to $250+, Wheat to $60+ |")
    lines.append("| `SMOOTHIE_SHOP` | **MILK**, **STRAWBERRY** | 1 each / 4 turns | 6 each / day (42 / week) | Rapidly drains Milk/Strawberry gluts |")
    lines.append("| `BAKERY` | WHEAT, EGG | 1 each / 4 turns | 6 each / day (42 / week) | Stabilizes Wheat prices at $55–$61 |")
    lines.append("| `BRUNCH_SPOT` | EGG, WHEAT, STRAWBERRY | 1 each / 4 turns | 6 each / day (42 / week) | High strawberry / egg demand |")
    lines.append("| `PET_CAFE` | CARROT | 2 Carrots / 4 turns | 12 Carrots / day | Drains Carrot supply |")
    lines.append("| `FARMERS_MARKET` | WHEAT, CARROT, TOMATO, STRAWBERRY | 1 each / 4 turns | 6 each / day | Multi-crop basket drainage |")
    lines.append("")
    lines.append("### 5.2 Why the Bot Missed Arbitrage Opportunities")
    lines.append("1. **Selling into Pre-Shop Void**: In episodes where `YARN_STORE` unlocked late (e.g. Day 12 or 15 in Episode 93981122), our bot began selling Wool on Days 6–10. Because zero shop demand existed, inventory accumulated above $I_0$ immediately, triggering quadratic decay before the shop opened.")
    lines.append("2. **Zero Fertilizer Sinks**: The bot treated Fertilizer identically to animal products, collecting and selling it daily. Because Fertilizer has zero shop consumption, 100% of fertilizer sales permanently eroded the price.")
    lines.append("3. **Lack of Drip-Feeding**: The bot dumped entire shed inventories in bulk orders (e.g. 15–20 units at once) rather than drip-feeding 2 units every 4 turns to match the exact town shop consumption rate.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 6. Opponent Comparative Study: The Abracadabra Architecture ($133.4k)")
    lines.append("")
    lines.append("In Episode 93981122, `Abracadabra` scored **$133,383.0** (outperforming our bot's $12,228.0 by +$121,155.0). Here is the full architectural breakdown of their strategy:")
    lines.append("")
    lines.append("```")
    lines.append("                                ABRACADABRA STRATEGIC FLYWHEEL ($133.4k)")
    lines.append("                                ")
    lines.append("    +--------------------------------------------------------------------------------+")
    lines.append("    | Phase 1: High-Yield Crop Nursery (Days 0-10)                                   |")
    lines.append("    | - Planted 127 Wheat, 34 Strawberry, 20 Melon                                   |")
    lines.append("    | - Deployed 947 Water actions + 64 Fertilizer applications                      |")
    lines.append("    | - Harvested 394 crops (Generated $58.1k Wheat, $57.3k Strawberry, $25.8k Melon)|")
    lines.append("    +--------------------------------------------------------------------------------+")
    lines.append("                                           │")
    lines.append("                                           ▼")
    lines.append("    +--------------------------------------------------------------------------------+")
    lines.append("    | Phase 2: High-Margin Livestock Multi-Stream (Days 10-25)                       |")
    lines.append("    | - Built 14 Pastures (10 Cows, 4 Sheep)                                         |")
    lines.append("    | - Wheat harvest fed animals at zero market buy cost (saved $25,000+ cash)      |")
    lines.append("    | - Generated $30.3k Milk + $14.7k Wool + $65.9k Fertilizer orders               |")
    lines.append("    +--------------------------------------------------------------------------------+")
    lines.append("                                           │")
    lines.append("                                           ▼")
    lines.append("    +--------------------------------------------------------------------------------+")
    lines.append("    | Phase 3: Town Shop Synchronized Multi-Channel Arbitrage                        |")
    lines.append("    | - Liquidated 5 distinct commodity streams into matching Town Shop demand       |")
    lines.append("    | - Total Gross Revenue Realized: $252,700+ -> Net Terminal Bank: $133,383.0     |")
    lines.append("    +--------------------------------------------------------------------------------+")
    lines.append("```")
    lines.append("")
    lines.append("### Comparative Metric Matrix: Our Bot vs Abracadabra (Episode 93981122)")
    lines.append("| Strategic Dimension | `alfphafarm` (Our Bot) | `Abracadabra` (Opponent) | Variance & Impact |")
    lines.append("| :--- | :--- | :--- | :--- |")
    lines.append("| **Final Net Worth** | **$12,228.0** | **$133,383.0** | +$121,155.0 (Abracadabra win) |")
    lines.append("| **Quadrants Unlocked** | 4 / 4 | 3 / 4 | Bot over-expanded land early ($7,000 spent) |")
    lines.append("| **Crops Planted** | **0 crops** | 187 crops (127 Wheat, 34 Strawberry, 20 Melon) | Missing entire $141k crop revenue stream |")
    lines.append("| **Crops Harvested** | 103 | 394 | 4x higher harvest volume |")
    lines.append("| **Water / Irrigation** | 0 | 947 actions | High-yield crop growth with zero dehydration |")
    lines.append("| **Fertilizer Applied** | 0 | 64 actions | Boosted Strawberry / Melon yields by 2x |")
    lines.append("| **Wheat Purchases** | Bought 424 Wheat ($19,456) | Bought 522 Wheat (Self-produced 1,138) | Opponent monetized internal feed supply |")
    lines.append("| **Strawberry Revenue**| $0.0 | **$57,309.0** | Huge high-margin cash generator |")
    lines.append("| **Wheat Sales Revenue**| $17,448.0 | **$58,113.0** | Drained Bakery & Pizza Shop demand |")
    lines.append("| **Wool Realized Price**| $91.49 / unit | $122.82 / unit | Opponent sold before price collapse |")
    lines.append("| **Milk Realized Price**| $70.05 / unit | $108.60 / unit | Bot sold into $9 trough |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 7. Strategic & Algorithmic Prescriptions for Next Submission")
    lines.append("")
    lines.append("Based on this quantitative forensic audit, we formulate 4 architectural upgrades for the next model submission:")
    lines.append("")
    lines.append("### 1. Smart Liquidity Drip-Feeding & Price-Aware Selling Thresholds")
    lines.append("- **Rule**: Never execute bulk `SELL` orders if market inventory $I(t) > I_0$.")
    lines.append("- **Threshold Gating**: Gate Wool sales to $P_{\\text{Wool}} \\ge \\$180$, Milk sales to $P_{\\text{Milk}} \\ge \\$180$, and Melons to $P_{\\text{Melon}} \\ge \\$220$.")
    lines.append("- **Rate Limiting**: When Town Shops are active, limit sales to **2 units every 4 turns** for single-product shops and **1 unit every 4 turns** for multi-product shops, perfectly matching town demand without triggering quadratic price decay.")
    lines.append("")
    lines.append("### 2. Strategic Fertilizer Internal Utilization")
    lines.append("- **Problem**: Dumping Fertilizer yields $< \\$10$ per unit in the mid-to-late game.")
    lines.append("- **Solution**: Never sell Fertilizer when $P_{\\text{Fert}} < \\$40$. Instead, deploy Farmhands to apply Fertilizer onto Strawberry and Melon tiles to double their yield, capturing **$120–$250 per unit** in crop value rather than $1 in market scrap.")
    lines.append("")
    lines.append("### 3. Crop-Pastoral Hybridization (The Abracadabra Flywheel)")
    lines.append("- Transition from pure pastoralism (0 crops) to a **Hybrid 4-Quadrant Ecosystem**:")
    lines.append("  - **Quadrant NW**: 10–12 Wheat tiles (providing 100% internal feed for livestock, eliminating $20k Wheat import cost).")
    lines.append("  - **Quadrant NE**: High-value Strawberry / Melon garden (fertilized for 2x yield, capturing $50k+ cash).")
    lines.append("  - **Quadrants SW & SE**: 16–20 Pastures (Cows + Sheep with daily CARE multipliers).")
    lines.append("")
    lines.append("### 4. Dynamic Town Shop Order Tracking")
    lines.append("- Ingest `obs['town']['unlocked_shops']` directly into the MCTS Macro Policy.")
    lines.append("- When `ICE_CREAM_SHOP` or `PIZZA_SHOP` opens, prioritize Milk and Strawberry liquidity.")
    lines.append("- When `YARN_STORE` opens, release held Wool reserves to capture the $240+ price spike.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Report compiled autonomously by Quantitative Match Replay & Market Dynamics Forensic Analyst.*")
    
    report_content = "\n".join(lines)
    os.makedirs(os.path.dirname(REPORT_FILE), exist_ok=True)
    with open(REPORT_FILE, "w", encoding="utf-8") as f:
        f.write(report_content)
        
    print(f"Report written successfully to {REPORT_FILE} ({len(lines)} lines, {len(report_content)} bytes).")

if __name__ == '__main__':
    build_report()
